### ISSUE TITLE
adding images to readme

### ISSUE THREAD

**Issue by shimwell** [fusion-energy/model_benchmark_zoo#8]
![Screenshot from 2023-08-22 14-54-00](https://github.com/fusion-energy/model_benchmark_zoo/assets/8583900/aea2582b-1d5f-40b1-a77b-bef79dce50da)
![Screenshot from 2023-08-22 14-53-21](https://github.com/fusion-energy/model_benchmark_zoo/assets/8583900/ef8696dd-adbc-4fd8-bd44-c5304e1d0709)
![Screenshot from 2023-08-22 14-52-59](https://github.com/fusion-energy/model_benchmark_zoo/assets/8583900/5e711a8b-a3db-4476-8f56-03a620d74b93)
![Screenshot from 2023-08-22 14-52-31](https://github.com/fusion-energy/model_benchmark_zoo/assets/8583900/20dee8fb-5199-4fc2-86a7-00452b6bdc89)

**Comment by shimwell** [comment]
![Screenshot from 2023-11-22 10-55-19](https://github.com/fusion-energy/model_benchmark_zoo/assets/8583900/c18e3345-52ec-4253-baa8-e1dbe2a52944)

**Comment by shimwell** [comment]
![Screenshot from 2023-11-24 22-27-05](https://github.com/fusion-energy/model_benchmark_zoo/assets/8583900/565d13fa-e8b8-4d0a-9a38-f625c225da3c)

**Comment by shimwell** [comment]
![torus_csg_cad](https://github.com/fusion-energy/model_benchmark_zoo/assets/8583900/3d744503-f0bc-4699-8646-557e2aa88209)

**Comment by davidepettinari** [comment]
![Image](https://github.com/user-attachments/assets/2c9a178f-88f9-43d5-a3f2-bed519a375f8)

**Comment by davidepettinari** [comment]
![Image](https://github.com/user-attachments/assets/eb543048-77d0-4b6c-8e24-36ff6d47f379)
